version: '3.8'

services:
  kaspa-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=${PORT:-8080}
      - VERBOSE=${VERBOSE:-1}
      - SEED_NODE=${SEED_NODE:-kaspadns.kaspacalc.net:16111}
      - SEED_NODE_1=${SEED_NODE_1:-}
      - SEED_NODE_2=${SEED_NODE_2:-}
      - SEED_NODE_3=${SEED_NODE_3:-}
      
      - IP_GEOLOCATION_TOKEN=${IP_GEOLOCATION_TOKEN:-}
      
      - MAX_CONCURRENT_CONNECTIONS=${MAX_CONCURRENT_CONNECTIONS:-250}
    volumes:
      - kaspa-data:/app/data
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "coolify.managed=true"

volumes:
  kaspa-data:
    driver: local

