# fly.toml file generated for kaspa-node-crawler on 2023-04-17T01:03:38-04:00

app = "kaspa-node-crawler"
primary_region = "ewr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
